apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  runtime-env.js: |
    window.__runtime_config__ = {
      MEMBER_URL: 'http://dg0305.20.214.196.128.nip.io/api/auth',
      MYSUB_URL: 'http://dg0305.20.214.196.128.nip.io/api/mysub',
      RECOMMEND_URL: 'http://dg0305.20.214.196.128.nip.io/api/recommend'
    };
